spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.19.128:3306/esTest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
  jpa:
    hibernate:
      ddl-auto: update